AdvertisingAgency/Controllers/CartController.cs
using AdvertisingAgency.Models.Date;
using AdvertisingAgency.Models.ViewModels.Account;
using AdvertisingAgency.Models.ViewModels.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AdvertisingAgency.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        //Viewing the shopping cart (Просмотр корзины)
        public ActionResult Index()
        {
            // Cart VM type list declaration (if the session is empty, a new sheet is created)
            // (Объявление list типа CartVM (если сессия пуста создаётся новый лист))
            var cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();

            //Checking the bucket = 0 or not (Проверка корзины = 0 или нет)
            if (cart.Count == 0 || Session["cart"] == null)
            {
                ViewBag.Message = "Your shopping cart is empty please do something about it.";
                return View();
            }

            // The amount and its entry in the ViewBag
            // (Сумма и ее запись во ViewBag)
            int total = 0;

            foreach (var item in cart)
            {
                total += item.Total;
            }

            ViewBag.GrandTotal = total;

            //(Returning a View) Возврат представления
            return View(cart);
        }

        // partial view in the upper right corner with the data about the ads in the shopping cart
        // (частичное представление в верхнем правом углу с данными о рекламе в корзине)
        public ActionResult CartPartial()
        {
            //Объявление модели CartVM
            CartVM model = new CartVM();

            //Объявление переменной количества
            int qty = 0;

            //Объявление переменной цены
            int price = 0;

            //Проверка сессии
            if (Session["cart"] != null)
            {
                //Получение общего количества товаров и цену
                var list = (List<CartVM>) Session["cart"];

                foreach (var item in list)
                {
                    qty += item.Quantity;
                    price += item.Quantity * item.Price;
                }

                model.Quantity = qty;
                model.Price = price;
            }
            else
            {
                //Или цена и кол-во равны 0
                model.Quantity = 0;
                model.Price = 0;
            }
            
            //Возврат частичного представления с моделью
            return PartialView("_CartPartial", model);
        }

        //Добавление рекламы в корзину
        public ActionResult AddToCartPartial(int id)
        {
            //Объявление List типа CartVM   (если сессия пуста создаётся новый лист)
            List<CartVM> cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();

            //Объявление модели CartVM
            CartVM model = new CartVM();

            using (Db db = new Db())
            {
                //(Getting ads) Получение рекламы
                ProductDTO product = db.Products.Find(id);

                // Checking whether an ad is in the shopping cart (Проверка нахождения рекламы в корзине)
                var productInCart = cart.FirstOrDefault(x => x.ProductId == id);

                //If not, then adding the product to the cart (Если нет, то добавление товара в корзину)
                if (productInCart == null)
                {
                    cart.Add(new CartVM()
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        Quantity = 1,
                        Price = product.Price,
                        Image = product.ImageName
                    });
                }

                // If there is, adding a unit of goods (Если есть, добавление единицы товара)
                else
                {
                    productInCart.Quantity++;
                }
            }

            // If there is, adding a unit of goods (Получение общего кол-ва рекламы, цену и добавление данных в модель)
            int qty = 0;
            int price = 0;

            foreach (var item in cart)
            {
                qty += item.Quantity;
                price += item.Quantity * item.Price;
            }

            model.Quantity = qty;
            model.Price = price;

            //Saving the bucket state to a session (Сохранение состояния корзины в сессию)
            Session["cart"] = cart;

            // (Returning a partial view with a model) Возврат частичного представления с моделью
            return PartialView("_AddToCartPartial", model);
        }

        //GET: /cart/IncrementProduct
        //Increase the number of products (Увеличить кол-во товаров)
        public JsonResult IncrementProduct(int productId)
        {
            //Объявление list cart
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                //Получение модели CartVM из list
                CartVM model = cart.FirstOrDefault(x => x.ProductId == productId);

                //Добавление количества
                model.Quantity++;

                //Сохранение необходимых данных
                var result = new { qty = model.Quantity, price = model.Price };

                //возврат Json ответ с данными
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        //GET: /cart/DecrementProduct
        //Уменьшить кол-во товаров
        public ActionResult DecrementProduct(int productId)
        {
            //Объявление list cart
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                //Получение модели CartVM из list
                CartVM model = cart.FirstOrDefault(x => x.ProductId == productId);

                //Убавление количества
                if (model.Quantity > 1)
                    model.Quantity--;
                else
                {
                    model.Quantity = 0;
                    cart.Remove(model);
                }

                //Сохранение необходимых данных
                var result = new { qty = model.Quantity, price = model.Price };

                //возврат Json ответ с данными
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        //GET: /cart/RemoveProduct
        //Удалить товар из корзины
        public void RemoveProduct(int productId)
        {
            //Объявление list cart
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                //Получение модели CartVM из list
                CartVM model = cart.FirstOrDefault(x => x.ProductId == productId);

                cart.Remove(model);
            }
        }

        //GET: /cart/order
        //Оформить заказ
        [HttpGet]
        public ActionResult Order()
        {
            //Получение имени пользователя
            string userName = User.Identity.Name;

            //Объявление модели
            UserProfileVM model;

            if (userName != "")
            {
                using (Db db = new Db())
                {
                    //Получение пользователя
                    UserDTO dto = db.Users.FirstOrDefault(x => x.Username == userName);

                    //Инициализируем модель данными
                    model = new UserProfileVM(dto);
                }
            }
            else
            {
                //Оставляем модель пустой
                model = new UserProfileVM();

                //Установка сообщения в Tempdata
                TempData["M"] = "To place an order, log in to your account!";
            }

            //Возврат модели в представление
            return View("Order", model);
        }

        //Отправка заказа на почту
        public bool ProcessOrder(List<CartVM> cart, UserVM UserInfo)
        {
            using (var smtpClient = new SmtpClient())
            {
                smtpClient.EnableSsl = true;
                smtpClient.Host = "smtp.mail.ru";
                smtpClient.Port = 25;
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Credentials = new NetworkCredential("luboyerajoel200@gmail.com", "pass1996");


               // smtpClient.DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory;
               // smtpClient.PickupDirectoryLocation = @"c:\PROmedia_emails";
               // smtpClient.EnableSsl = false;

                StringBuilder body = new StringBuilder()
                    .AppendLine("New order")
                    .AppendLine("---")
                    .AppendLine("Advertisement:");

                var Total = 0;
                foreach (var item in cart)
                {
                    body.AppendFormat("{0} {1}\t{2} * {3} (итого: {4:c}",
                        item.ProductId, item.ProductName, item.Quantity, item.Price, item.Total);
                    Total += item.Total;
                }

                body.AppendFormat("Total cost: {0:c}", Total)
                    .AppendLine("---")
                    .AppendLine("User data:")
                    .AppendLine(UserInfo.FirstName)
                    .AppendLine(UserInfo.LastName)
                    .AppendLine(UserInfo.EmailAdress)
                    .AppendLine(UserInfo.Username);

                MailMessage mailMessage = new MailMessage(
                                       "lubotech@gmail.com",          // От кого 
                                       "luboyerajoel200@gmail.com",       // Кому  пароль 2020pass
                                       "A new order has been sent!",        // Тема

AdvertisingAgency/Controllers/PagesController.cs
using AdvertisingAgency.Models.Date;
using AdvertisingAgency.Models.ViewModels.Pages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdvertisingAgency.Controllers
{
    public class PagesController : Controller
    {
        // GET: Index/{Page}
        public ActionResult Index(string page = "")
        {
            //Получение/установка краткого заголовка Slug
            if (page == "")
                page = "home";

            //Объявление модели и класса DTO
            PageVM model;
            PagesDTO dto;

            //Проверка доступа страницы
            using (Db db = new Db())
            {
                if (!db.Pages.Any(x => x.Slug.Equals(page)))
                    return RedirectToAction("Index", new { page = "" });
            }

            //Получение DTO страницы
            using (Db db = new Db())
            {
                dto = db.Pages.Where(x => x.Slug == page).FirstOrDefault();
            }

            //Установка заголовка страницы
            ViewBag.PageTitle = dto.Title;

            //Заполнение модели данными
            model = new PageVM(dto);

            //Возврат представления с моделью
            return View(model);
        }

        public ActionResult PagesMenuPartial()
        {
            //Инициализация list PageVM
            List<PageVM> pageVMList;

            //Получение все страниц кроме home
            using (Db db = new Db())
            {
                pageVMList = db.Pages.ToArray().OrderBy(x => x.Sorting).Select(x => new PageVM(x)).ToList();
            }

            //Возврат частичного представления с листом данных
            return PartialView("_PagesMenuPartial", pageVMList);
        }

    }
}

AdvertisingAgency/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Advertising Agency</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                @Html.Action("PagesMenuPartial", "Pages")
                <!--If the user is logged in-->
                @if (Request.IsAuthenticated)
                {
                    <li> @Html.ActionLink("Log out", "Logout", "Account", null, new { @class = "navbar-text", style = "text-decoration: none" })</li>
                }
                else
                {
                    //If an unauthorized user is on the login page, the link is active
                    //Если неавторизованный пользователь находится на странице login, ссылка активна
                    if (ViewBag.Title == "Login")
                    {
                        <li class="nav-item">  @Html.ActionLink("Sign in", "Login", "Account", null, new { @class = "nav-link", style = "text-decoration: none" }) </li>
                    }
                    //If an unauthorized user is on any other page, the link is not active
                    //Если неавторизованный пользователь находится на любой другой странице, ссылка не активна
                    else
                    {
                        <li class="nav-item"> @Html.ActionLink("Sign in", "Login", "Account", null, new { @class = "navbar-text", style = "text-decoration: none" }) </li>
                    }
                }

                @if (Request.IsAuthenticated)
                {
                    <li> @Html.Action("UserNavPartial", "Account", new { area = "" }) </li>
                }
            </ul>
            <span class="navbar-text">
                @Html.Action("CartPartial", "Cart")
            </span>
        </div>
    </nav>

    <div class="container body-content">
        <div class="row">

            <div class="col-sm-12 col-md-3 list-group">
                @Html.Action("CategoryMenuPartial", "Agency")
            </div>

            @if (ViewBag.Sidebar == "Yes")
            {
                <div class="col">
                    @RenderBody()
                </div>

                <div class="col-sm-12 col-md-3">
                    @Html.Action("SidebarPartial", "Pages")
                </div>
            }
            else
            {
                <div class="col">
                    @RenderBody()
                </div>
            }
        </div>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Advertising agency "LUBOTECH ADVERTS"</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/scripts")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>